# Generated by Django 4.0.1 on 2022-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('RID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.BigAutoField(primary_key=True, serialize=False)),
                ('productTitle', models.CharField(max_length=100)),
                ('productDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.BigAutoField(primary_key=True, serialize=False)),
                ('pwToekn', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
            ],
        ),
    ]
