# Generated by Django 4.0.1 on 2022-02-13 16:57

from django.db import migrations, models
import trading.models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_delete_chat_comment_nickname_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productThumbnail',
            field=models.ImageField(blank=True, upload_to=trading.models.upload_to_func),
        ),
    ]
